# gazelle:ignore
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "const.go",
        "util.go",
    ],
    importpath = "github.com/GoogleCloudPlatform/docker-credential-gcr/test",
    visibility = ["//visibility:public"],
)
