on: [push, pull_request]
name: Test

permissions:
  contents: read

jobs:
  go-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: Checkout code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          persist-credentials: false
      - name: Build
        run: go build
      - name: Build in GOPATH
        if: ${{ matrix.os != 'windows-latest' }}
        run: go build -o $(go env GOPATH)/bin/docker-credential-gcr main.go
      - name: Vet
        run: go vet ./...
      - name: Test mac/ubuntu
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          go test -timeout 10s -v ./...
          go test -race -timeout 10s -v ./...
        env:
          MallocNanoZone: 0
      - name: Test windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          go test -timeout 10s -v -tags=windows ./...
          go test -race -timeout 10s -v -tags=windows ./...
  goreleaser-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: false
      - name: Build GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: build --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
